displayName=Bank Clickbox Highlighter
author=Brad
description=Highlights bank clickboxes, with options for deposit boxes and Group storage
tags=bank,booth,chest,highlight
plugins=com.bankhighlighter.BankHighlighterPlugin
build=standard
